server:
  port: 8083


cube:
  url: https://u3w.com/cubeServer/aigc
  wssurl: ws://127.0.0.1:8081/websocket?clientId=play-ylf100002
  datadir: C:\AGI\user-data-dir
  uploadurl: https://u3w.com/cubeServer/common/upload




