server:
  port: 8083


cube:
  url: https://127.0.0.1:8083/cubeServer/aigc
  wssurl: wss://127.0.0.1:8083/cubeServer/websocket?clientId=play-你的主机ID  #主机ID建议使用字母+数字组合，例如play-user01
  datadir: C:\AGI\user-data-dir
  uploadurl: https://127.0.0.1:8083/cubeServer/common/upload




